### ISSUE TITLE
The dependencies in bower.json get overwritten by package.json dependencies

### ISSUE THREAD

**Issue by hvoecking** [bevry/projectz#51]
When executing `compile` in a project where you have a bower file, the `dependencies` and the `devDevpendencies` get overwritten by the ones specified in package.json

**Comment by balupton** [comment]
Overwritten or merged?

**Comment by hvoecking** [comment]
They're overwritten, I wrote a [test case](https://github.com/hvoecking/projectz/commit/d99e3312eb52c06d0eced997d0107d4077685d38), this is the output:
```
FAILURE: 1/2 tests ran successfully; 1 failed, 0 incomplete, 1 errors

Error #1:
projectz-dependencies ➞  files ➞  bower.json
AssertionError: expected '{"dependencies":{"package-dependency-1":"version","package-dependency-2":"version"},"devDependencies":{"package-dev-dependency-1":"version","package-dev-dependency-2":"version"}}' to equal '{"dependencies":{"bower-dependency-1":"version","bower-dependency-2":"version"},"devDependencies":{"bower-dev-dependency-1":"version","bower-dev-dependency-2":"version"}}'
    at /tmp/projectz/out/test/dependencies-test.js:51:59
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

/tmp/projectz/Cakefile:103
      throw err;
            ^
Error: Process exited with error status code
  at ChildProcess.<anonymous> (/tmp/projectz/Cakefile:92:15)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:755:16)
  at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

Are they supposed to get merged?

**Comment by pflannery** [comment]
I get the same problem.
I don't think we should to try to merge npm and bower dependencies but the license, description and keywords etc should be merged (currently not working for bower)
